### ISSUE TITLE
PYPI secret key

### ISSUE THREAD

**Issue by jGaboardi** [pysal/inequality#34]
@sjsrey In order to set up the `release` workflow, I need to have "MANAGE" access permissions in PYPI. It seems when I was granted permissions to `inequality` (and `splot` + `mapclassify`) it was only partial, and I don't have the ability to generate secret tokens (needed for the release GHA). Would it be possible to update these permissions?

<img width="400" alt="Screenshot 2022-11-27 at 2 04 29 PM" src="https://user-images.githubusercontent.com/8590583/204154782-0209ddfe-2d73-4099-a4d8-2a2401a30e20.png">

**Comment by sjsrey** [comment]
Should be changed now.

**Comment by jGaboardi** [comment]
Yes, can confirm I now have management access. Thanks!
