### ISSUE TITLE
Nijkamp & Poot (2013)?

### ISSUE THREAD

**Issue by jGaboardi** [pysal/inequality#36]
I was not able to find the paper associated the [Nijkamp & Poot (2013) citation](https://github.com/pysal/inequality/blob/34638a04f347ac4984d10658e6678cf6a8ccf9d9/inequality/_indices.py#L2). Is it possibly [Ozgen, Nijkamp, & Poot (2013)](https://www.econstor.eu/bitstream/10419/69390/1/73402116X.pdf)?

@sjsrey

**Comment by jGaboardi** [comment]
I want to ping this again to see about resolving. Seems like to be an easy one to close out.

cc @knaaptime

**Comment by sjsrey** [comment]
Dani did the inequality indices while working with Nijkamp so he'd be the one to ask.

**Comment by jGaboardi** [comment]
@darribas Can you chime in here?

**Comment by darribas** [comment]
hey! I'm not sure what the 2013 ref is now. My first thought was a working paper but that really looks like the 2015 one. I remember getting the idea for writing the suite of indices from a talk Jacques (Poot) did around 2013, so maybe that is what I wanted to refer to?

Looking into it, I can also see that the 2015 ref could probably be updated to the non-working paper version?

https://www.elgaronline.com/edcollchap/edcoll/9781783476800/9781783476800.00008.xml

```bibtex
@incollection{nijkamp2015cultural,
  title={Cultural diversity: a matter of measurement},
  author={Nijkamp, Peter and Poot, Jacques},
  booktitle={The economics of cultural diversity},
  pages={17--51},
  year={2015},
  publisher={Edward Elgar Publishing}
}
```

My view would be to remove the 2013 one perhaps?
