### ISSUE TITLE
`pysal/inequality` vs. `pysal/segregation`?

### ISSUE THREAD

**Issue by jGaboardi** [pysal/inequality#40]
At some point we should take a deep dive to figure out the overlap between `inequality` and `segregation`, and determine how much/if any of `inequality` can be consumed by `segregation` (or vice-versa). Or even if `inequality` should be entirely cannibalized by `segregation`.

**Comment by martinfleis** [comment]
I like that `inequality` is very lean package. `momepy` uses `Theil` and `Gini` and I would rather not depend on whole `segregation` here with `rvlib` et al as dependencies. But I can easily move those simple formulas over and not depend on any of those.

From a wider perspective, it makes sense to merge this stuff with something else, it is tiny and the last release was 4 years ago, so not even active.

**Comment by jGaboardi** [comment]
To be clear & transparent, I think that the most reasonable path forward is for `inequality` to remain its own package. I was simply throwing out some possible ideas. 

As for the maintenance side, I have been spending time cleaning `inequality` up over the last month and would very much like to get a fresh release out to be included in the next PySAL meta release.

**Comment by knaaptime** [comment]
serge and i have talked about this once or twice before. I tend to agree a merger makes sense

if it would help, I think its probably worthwhile to make rvlib an optional dependency (and fallback to the slower sampler otherwise), so segregation's [requirement footprint](https://github.com/pysal/segregation/blob/master/requirements.txt) should become pretty standard (i think quilt can go too)

**Comment by martinfleis** [comment]
> make rvlib an optional dependency

That would be good!

**Comment by sjsrey** [comment]
I think inequality and segregation should remain separate. 

There is a bunch of inequality enhancements  I have code for but have not pushed up, related to an nsf project that just is winding down.

**Comment by jGaboardi** [comment]
The big boss has spoken. I'll close this out.
