### ISSUE TITLE
`v1.0.1` release

### ISSUE THREAD

**Issue by jGaboardi** [pysal/inequality#45]
I'd like to cut a ~~`v1.1.0`~~ release for this month's PySAL meta release. Anything else to add/adjust/etc. before that?

**Comment by martinfleis** [comment]
This would be about documentation only? Then it does not qualify for a minor I guess and should be 1.0.1 instead.

**Comment by jGaboardi** [comment]
It's a bit more than docs; infrastructure and such. I was on the fence about it either being a minor release or patch release. I don't have a strong opinion either way though. If nobody else chimes in in the next several days we can go ahead with `v1.0.1`.

**Comment by martinfleis** [comment]
Infrastructure is irrelevant for a release, no? How we manage our CI is not affecting the package a user downloads from PyPI. I don't really mind I just thought that per semver we may not fulfil the minor criteria.

**Comment by jGaboardi** [comment]
Fair enough. Let's go with `v1.0.1`.

**Comment by jGaboardi** [comment]
No release action ever made it into `inequality`. I'll work on that.

**Comment by weikang9009** [comment]
I do not have further items to add to the release. Thanks @jGaboardi

**Comment by jGaboardi** [comment]
I'll start with a `v1.0.1rc1` since there seem to be quite a few kinks to work out in other packages.

**Comment by jGaboardi** [comment]
Done.
