### ISSUE TITLE
CI adjustment needed for `numpy>=2.1.0.dev0`

### ISSUE THREAD

**Issue by jGaboardi** [pysal/inequality#67]
* We are seeing [14 failures in DEV CI](https://github.com/pysal/inequality/actions/runs/8809200019/job/24179611128) due upstream [`numpy>=2.1.0.dev0`](https://github.com/pysal/inequality/actions/runs/8809200019/job/24179611128#step:3:185).
* All are docstring `Examples` failures, so maybe we simply cast as vanilla floats there?

**Comment by sjsrey** [comment]
Thanks for flagging this.

I think we should deprecate the `_indices.py` module as much of this is now in segregation anyway and we have always had this as a private module in `inequality`.

Moving this out of `inequality` would allow for a clearer separation between `segregation` and `inequality` as well.

**Comment by jGaboardi** [comment]
Resolved in #69
