### ISSUE TITLE
add `matplotlib` as a dependency

### ISSUE THREAD

**Issue by jGaboardi** [pysal/inequality#79]
xref https://github.com/pysal/inequality/pull/75#pullrequestreview-2275036652

Since we are using `matplotib` in `schutz` and [`pen`](https://github.com/pysal/inequality/blob/03ca5619d50839be8d0a68a427027530d971dcdd/inequality/pen.py#L47), perhaps it makes sense to just go ahead and make it a requirement?

**Comment by martinfleis** [comment]
Given splot will be dismantled, it is quite likely that we may want lib and esda depend on it as well, so it is probably fine. Just needs to be done explicitly.
